# Makefile.include
# Platform-dependent settings for HW1
#

#CC = icc
CC = pgcc

#COPTFLAGS = -O2
COPTFLAGS = 

CPPFLAGS = 

CFLAGS = -acc -Minfo:accel -fast -mp -Minfo $(COPTFLAGS)
#CFLAGS = -Wall $(COPTFLAGS)

#LINKER = icc
LINKER = pgcc

LDFLAGS = -lm -lpthread


